### PR TITLE
Add bitbucket support

### PR DESCRIPTION
**Pull request by rdark**

### CODE REVIEW

**Comment by martinemde** [comment]
Thank you for contributing!

I fixed the `last_comment` problem by upgrading rspec. I'll merge this and then un-pin rake.

I'll push version `0.4.0` in following SemVer: "backwards compatible functionality is introduced to the public API."

**Comment by rdark** [comment]
@martinemde thanks!

**Comment by martinemde** [comment]
@rdark Are you using gitable in CircleCI? That's really cool to hear. We use CircleCI at my work.

**Comment by martinemde** [comment]
0.4.0 is released. Thanks again.

**Pull request merged**
